- hosts:
    - my_web_server
  tasks:
    - name: Ansible command to make a directory
      command: mkdir SampleDir
      args:
        creates: SampleDir
    - name: Install a list of packages
      sudo: yes
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - docker
    - name: Ansible command check the directory made
      command: ls
      register: listOutput
    - debug: msg="{{ listOutput.stdout }}"

    - name: Start Docker Service
      command: sudo service docker start

    - name: pull Product Recall Image
      docker_image:
        name: shlokkapoor/productrecall
        source: pull
    
    - name: run docker image
      command: sudo docker run --rm -p 8000:8000 shlokkapoor/productrecall
