- hosts:
    - my_web_server
  tasks:
    - name: Ansible command to make a directory
      command: mkdir SampleDir
      args:
        creates: SampleDir
    - name: Install a list of packages
      sudo: yes
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - docker
    - name: Ansible command check the directory made
      command: ls
      register: listOutput
    - debug: msg="{{ listOutput.stdout }}"

    - name: Start Docker Service
      command: sudo service docker start

    - name: pull docker image
      command: sudo docker pull shlokkapoor/productrecall

    - name: stop docker container
      command: if [ -z $(sudo docker ps -a -q --filter ancestor=shlokkapoor/productrecall) ]; then echo hi; else sudo docker stop $(sudo docker ps -a -q --filter ancestor=shlokkapoor/productrecall); fi

    - name: run docker image in detached mode
      command: sudo docker run -d --rm -p 8000:8000 shlokkapoor/productrecall
