- hosts:
    - my_web_server
  tasks:
    - name: Ansible command to make a directory
      command: mkdir SampleDir
      args:
        creates: SampleDir
    - name: Install a list of packages
      become_method: sudo
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - docker
    - name: Ansible command check the directory made
      command: ls
      register: listOutput
    - debug: msg="{{ listOutput.stdout }}"
