- hosts:
    - my_web_server
  tasks:
    - name: Ansible command to make a directory
      command: mkdir SampleDir
      args:
        creates: SampleDir
    - name: Ansible command check the directory made
      command: ls
      register: listOutput
    - debug: msg="{{ listOutput.stdout }}"
